### ISSUE TITLE
I ask you to update the sdk to the actual version, because there are errors when connecting.

### ISSUE THREAD

**Issue by Vokaimoh** [potatojam/defold-vkbridge#3]
![image](https://github.com/potatojam/defold-vkbridge/assets/133861101/a2835e59-dd39-4161-981c-bdd1af414f62)

There is also a new functionality of advertising banners  https://dev.vk.com/ru/games/monetization/ad/banners 
![image](https://github.com/potatojam/defold-vkbridge/assets/133861101/55014a30-876c-4feb-ac06-c2adbffb3c63)

**Comment by AGulev** [comment]
Fixed in https://github.com/potatojam/defold-vkbridge/releases/tag/1.0.3
